config/routes.rb
Deargovernment::Application.routes.draw do
  
  root 'concerns#index'

  resources :concerns

end

app/models/concern.rb
class Concern < ActiveRecord::Base
	
	validates :location, :description, presence: true
	validates :name, presence: true, length: { maximum: 80 }

	geocoded_by :location

  before_save :generate_reference_code, :geocode

  private

  def generate_reference_code
  	self.reference_code = rand(36**10).to_s(36) if self.reference_code.nil?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns_controller.rb
class ConcernsController < ApplicationController
  def index
  	@concerns = Concern.all
  end

  def new
  	@concern = Concern.new
  end

  def edit
  	@concern = Concern.find_by_id(params[:id])
  end

  def create
  	@concern = Concern.new(concern_params)
  	
  	if @concern.save
  		flash[:success] = "A new concern has been saved."
  		redirect_to concerns_path
  	else
  		flash[:error] = "The concern could not be saved."
  		render 'new'
  	end
  end

  def update
  	@concern = Concern.find_by_id(params[:id])
  	if @concern.update_attributes(concern_params)
  		flash[:success] = "A new concern has been saved."
  		redirect_to concerns_path
  	else
  		flash[:error] = "The concern could not be updated."
  		render 'edit'
  	end
  end

  def destroy
  	@concern = Concern.find_by_id(params[:id])
    @concern.destroy
    flash[:success] = "Concern removed."
    redirect_to concerns_path
  end

  private

  def concern_params
    params.required(:concern).permit(:name, :description, :location)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerns_helper.rb
module ConcernsHelper
end

app/views/concerns/_concern_form.html.haml
%strong
	= @concern.name

= simple_form_for @concern do |f|
	= f.input :name
	= f.input :description
	= f.input :location
	= f.submit 'Submit'

app/views/concerns/edit.html.haml
%h1
	Edit a Concern

%div.concern-form
	= render 'concerns/concern_form'

app/views/concerns/index.html.haml
%h1
	Recent Concerns
	%table
		%th
			%td Name
			%td Description
			%td Location
			%td Longitude
			%td Latitude
		- @concerns.each do |concern|
			%tr#concern-item
				%td= concern.name
				%td= concern.description
				%td= concern.location
				%td= concern.longitude
				%td= concern.latitude
				%td= link_to 'Edit', edit_concern_path(concern)
				%td= link_to 'Delete', concern, method: :delete

app/views/concerns/new.html.haml
%h1
	Raise a Concern

%div.concern-form
	= render 'concerns/concern_form'

app/views/layouts/application.html.haml
!!! 5
%html
	%head
		%title
			Dear Government | Enable Government Action
	  
		= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
		= javascript_include_tag "application", "data-turbolinks-track" => true
		= csrf_meta_tags

	%body

		%section.errors
			- flash.each do |key, value|
				%div{id: key}
					= value

		%section.container
			%div.page
				= yield